# Version of the BuildSpec standard you are using.
version: 0.2

# Build phases are pre-defined, you can't add or
# or rename them, and they always run in the same
# order. However, they are optional, so if you don't
# have any commands to run in a particular phase,
# there is no need to define that phase.
phases:
  install:
    commands:
      - echo Install packer
      - curl https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip > packer.zip
      - unzip packer.zip
  pre_build:
    commands:
      - echo Validating packer template
      - ./packer validate packer.json
  build:
    commands:
      - echo Building packer image
      - ./packer build -machine-readable packer.json | tee packer.log
      - if grep 'no artifacts were created' packer.log; then echo "Packer build failed"; exit 1; fi
  post_build:
    commands:
      - echo Saving AMI ID
      - tail -1 packer.log | grep -o ami.*$ | tee AMI_ID

# CodeBuild uploads any artifacts you specify in this
# section to your S3 output bucket.
artifacts:
  files:
    - packer.log
    - AMI_ID
