AWSTemplateFormatVersion: "2010-09-09"
Description: Launches a test EC2 instance for a new AMI

Parameters:
  AmiId:
    Type: String
    Description: AMI ID to launch test instance with
  NameTag:
    Type: String
    Description: Name tag value for the test instance
  PublicSubnet:
    Type: String
    Description: Subnet ID of a public subnet in which to launch instance
  SecurityGroup:
    Type: String
    Description: Security Group ID of a security group that allows inbound public HTTP

Outputs:
  URL:
    Value: !Sub "http://${EC2Instance.PublicDnsName}"

Resources:
   EC2Instance: 
      Type: "AWS::EC2::Instance"
      Properties: 
        ImageId:  !Ref "AMI_ID"
        InstanceType: t2.micro
        Tags:
          - Key: Name
            Value: !Ref "${NameTag}"
          - Key: Environment
            Value: "test"
        NetworkInterfaces: 
          - AssociatePublicIpAddress: "true"
            DeviceIndex: "0"
            GroupSet: 
              - Ref: !Ref "SecurityGroup"
            SubnetId: 
              Ref: !Ref "PublicSubnet"
